# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/centos-6.7"

  # config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 9200, host: 9200
  config.vm.network :forwarded_port, guest: 8000, host: 8000

  config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder "../data/elasticsearch2/logs", "/var/log/elasticsearch", :mount_options => [ "dmode=777", "fmode=777" ]
  config.vm.synced_folder "../data/elasticsearch2/plugins", "/usr/share/elasticsearch/plugins", :mount_options => [ "dmode=777", "fmode=777" ]

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.omnibus.chef_version = :latest

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.add_recipe "java"
    chef.add_recipe "elasticsearch"
    chef.json = {
      :java => {
        :install_flavor => "oracle",
        :jdk_version => 8,
        :oracle => {
          "accept_oracle_download_terms" => true
        }
      }
    }
  end

end
