# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-7.0"

  # config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 8000, host: 8000

  config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder "../data/fess/logs", "/opt/fess/logs", :mount_options => [ "dmode=777", "fmode=777" ]
  config.vm.synced_folder "../data/fess/logs", "/opt/fess/webapps/fess/WEB-INF/logs", :mount_options => [ "dmode=777", "fmode=777" ]

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.omnibus.chef_version = :latest

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks", "site-cookbooks"]
    chef.add_recipe "java"
    chef.add_recipe "mysql::server"
    chef.add_recipe "fess"
    chef.json = {
      :java => {
        :install_flavor => "oracle",
        :jdk_version => 8,
        :oracle => {
          "accept_oracle_download_terms" => true
        }
      },
      :mysql => {
        "enable_utf8" => true,
        "bind_address" => "127.0.0.1",
        "server_root_password" => "mysqldb",
        "server_repl_password" => "mysqldb",
        "server_debian_password" => "mysqldb"
      }
    }
  end

end
